version: '3'
services:
  nodeapp:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - mysql
    ports:
     - "8080:8080"

  redis:
    container_name: myapp-redis
    image: 'redis:4.0.11'
    restart: always
    ports:
     - "6379:6379"


  mysql:
    container_name: mysql
    image: 'mysql:5.7.28'
    restart: always
    ports:
     - "3306:3306"
    volumes:
      - "mysql:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'demo'
      MYSQL_USER: kafeel
      MYSQL_PASSWORD: 'demopassword'
  

volumes:
  mysql:
  
